
const strings = {
  login: {
    title: 'Estilistas',
    user: 'Usuario',
    password: 'Contraseña',
    submit: 'Entrar',
    forgotPasswordQuestion: '¿Olvidaste tu contraseña?',
    forgotPasswordLink: 'Click aquí',
    recoverPassword: 'Recuperar Contraseña',
    rememberedPasswordQuestion: '¿Recordaste tu contraseña?',
    rememberedPasswordLink: 'Click aquí',
    confirmPassword: 'Confirmar Contraseña',
    passwordChange: 'Establecer Contraseña',
  },
  error: {
    unauthorized: '',
    userNotFound: '',
    restorePassword: '',
    passwordLength: '',
    passwordMatch: '',
  },
  menu: {
    dashboard: 'Pánel de Control',
    locations: 'Sucursales',
    customers: 'Clientes',
    employees: 'Empleados',
    products: 'Productos',
  },
  location: {
    table: {
      name: 'Nombre',
      rfc: 'RFC',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      address: 'Dirección',
      empty: 'No se encontraron sucursales.',
      add: 'Agregar sucursal',
      edit: 'Editar sucursal',
      erase: 'Borrar sucursal',
      eraseDescription: name => `Se va a eliminar la sucursal "${name}". Esta acción no es reversible. ¿Deseas continuar?`,
    },
  },
  customer: {
    table: {
      location: 'Sucursal',
      name: 'Nombre',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      empty: 'No se encontraron clientes.',
      add: 'Agregar cliente',
      edit: 'Editar cliente',
      erase: 'Borrar cliente',
      eraseDescription: name => `Se va a eliminar al cliente "${name}". Esta acción no es reversible. ¿Deseas continuar?`,
    },
  },
  product: {
    table: {
      location: 'Sucursal',
      sku: 'SKU',
      name: 'Nombre',
      price: 'Precio',
      commission: 'Comisión',
      isService: '¿Es un servicio?',
      empty: 'No se encontraron productos.',
      add: 'Agregar producto',
      edit: 'Editar producto',
      erase: 'Borrar producto',
      eraseDescription: name => `Se va a eliminar el producto "${name}". Esta acción no es reversible. ¿Deseas continuar?`,
    },
  },
  employee: {
    table: {
      location: 'Sucursal',
      name: 'Nombre',
      phone: 'Teléfono',
      empty: 'No se encontraron empleados.',
      add: 'Agregar empleado',
      edit: 'Editar empleado',
      erase: 'Borrar empleado',
      eraseDescription: name => `Se va a eliminar al empleado "${name}". Esta acción no es reversible. ¿Deseas continuar?`,
    },
  },
  forms: {
    warning: 'Atención',
    save: 'Guardar',
    cancel: 'Cancelar',
    yes: 'Yes',
    no: 'No',
    location: {
      name: 'Nombre',
      rfc: 'RFC',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
      street: 'Calle',
      number: 'Número',
      city: 'Ciudad',
      state: 'Estado',
      zip: 'Código Postal',
    },
    employee: {
      location: 'Sucursal',
      name: 'Nombre',
      phone: 'Teléfono',
    },
    customer: {
      location: 'Sucursal',
      name: 'Nombre',
      email: 'Correo Electrónico',
      phone: 'Teléfono',
    },
    product: {
      location: 'Sucursal',
      sku: 'SKU',
      name: 'Nombre',
      price: 'Precio',
      commission: 'Comisión',
      isService: '¿Es un servicio?',
    },
  },
};

export default strings;